Feature/us3
WildCodeSchool/lyon-js-0320-p2-g1 pull request #32
Opened 2020-04-28 14:22 UTC by K0Si-003

2020-05-03 10:08 UTC, ComicScrip requested changes
La sélection des ingrédients fonctionne bien, mais je ne peux pas encore avoir des recommandations de cocktail comme dit dans l'US.

2020-05-03 17:25 UTC, AnaH-1907 commented
Hello Pierre, 
notre US était trop générale, nous l'avons modifiée, l'apparition de la page avec la recette du cocktail est maintenant pour une autre US (la 17 dans le product backlog).
Pour celle ci nous permettons à l'utilisateur de sélectionner les ingrédients qu'il a à sa disposition.

2020-05-04 16:24 UTC, ComicScrip approved these changes

2020-05-04 16:24 UTC, ComicScrip commented
> Hello Pierre,
> notre US était trop générale, nous l'avons modifiée, l'apparition de la page avec la recette du cocktail est maintenant pour une autre US (la 17 dans le product backlog).
> Pour celle ci nous permettons à l'utilisateur de sélectionner les ingrédients qu'il a à sa disposition.

OK je valide la partie sélection du coup :)

2020-05-04 16:25 UTC, merged